version: '3.8'

services:
  flyway:
    restart: on-failure
    image: flyway/flyway:7.5.3
    command: -url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB} -schemas=public -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    networks:
      - gcp

  api:
    container_name: demo-api
    build:
      context: ./
    image: demo-api
    restart: on-failure
    ports:
    - '8080:8080'
    depends_on:
      - flyway
    networks:
      - gcp
    volumes:
      - './:/src'

volumes:
  db:
    driver: local

networks:
  gcp:
    driver: bridge