spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSGREST_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

server:
  port: ${PORT:8080}
