spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost:5432}/${POSTGRES_DB:postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    baseline-on-migrate: true

management:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    path: /api-docs