name: Deploy

on:
  push:
    branches:
      - feature/deploy_do # TODO update to main

env:
  IMAGE_NAME: demo-api

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: 'gradle'
      - run: ./gradlew build --no-daemon

  push:
    needs: build

    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.push_image.outputs.VERSION_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build docker image
        run:  docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/demo

  deploy:
    needs: [ build, push ]

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: SSH connector
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME  }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            echo "Log into Docker"
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            echo "Run docker compose"
            docker-compose up --build -d
