name: Deploy

on:
  push:
    branches:
      - feature/deploy_do # TODO update to main

env:
  IMAGE_NAME: demo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: '18'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  push:
    needs: build

    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.push_image.outputs.VERSION_NAME }}

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build docker image
        run:  docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER }}/$IMAGE_NAME

      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USER }}/$IMAGE_NAME

  deploy:
    needs: [ build, push ]

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: SSH connector
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME  }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            echo "Log into Docker"
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
            echo "Run docker compose"
            docker-compose up --build -d
