name: Validate build on PR

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: '18'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build